May add extra fields in ServiceException
AODocs/endpoints-java pull request #13
Opened 2019-02-15 07:51 UTC by llbrt

- may enhance ServiceException with extra fields
- limit values to simple objects (nor array nor collection)
- add extra fields in error body
- add unit tests

2019-02-20 09:16 UTC, alarribeau requested changes
> Reviewed 6 of 6 files at r1.
> *[Reviewable](https://reviewable.io/reviews/aodocs/endpoints-java/13)* status: all files reviewed, 7 unresolved discussions (waiting on @clementdenis, @llbrt, and @RaHery)

___
*[endpoints-framework/src/main/java/com/google/api/server/spi/ServiceException.java, line 150 at r1](https://reviewable.io/reviews/aodocs/endpoints-java/13#-LZ98tOzBmP0ud0im9iB:-LZ98tOzBmP0ud0im9iC:bi62k3m) ([raw file](https://github.com/aodocs/endpoints-java/blob/2c102c362e04f4a0c94b1eead76b699c744de18c/endpoints-framework/src/main/java/com/google/api/server/spi/ServiceException.java#L150)):*
> ```Java
>     Preconditions.checkArgument(!EXTRA_FIELDS_RESERVED_KEYWORDS.contains(key), "The keyword '%s' is reserved", key);
>     Object prevValue = extraFields.put(key, value);
>     if (prevValue != null) {
> ```

(Would have written previousValue)
___
*[endpoints-framework/src/test/java/com/google/api/server/spi/ServiceExceptionTest.java, line 37 at r1](https://reviewable.io/reviews/aodocs/endpoints-java/13#-LZ99K5o9TPGPFtXJSNc:-LZ99K5o9TPGPFtXJSNd:bo1dg32) ([raw file](https://github.com/aodocs/endpoints-java/blob/2c102c362e04f4a0c94b1eead76b699c744de18c/endpoints-framework/src/test/java/com/google/api/server/spi/ServiceExceptionTest.java#L37)):*
> ```Java
>   public void testExtraFields() {
>     UnauthorizedException ex = new UnauthorizedException("");
>     ex.addExtraField("isAdmin", TRUE).addExtraField("userId", Integer.valueOf(12)).addExtraField("userName", "John Doe");
> ```

One addition by line would increase the readability and make the arrange bloc symmetric with the assertion bloc.
___
*[endpoints-framework/src/test/java/com/google/api/server/spi/ServiceExceptionTest.java, line 51 at r1](https://reviewable.io/reviews/aodocs/endpoints-java/13#-LZ99vjpDvFN-yXaxdsZ:-LZ99vjpDvFN-yXaxds_:b-3dr0rl) ([raw file](https://github.com/aodocs/endpoints-java/blob/2c102c362e04f4a0c94b1eead76b699c744de18c/endpoints-framework/src/test/java/com/google/api/server/spi/ServiceExceptionTest.java#L51)):*
> ```Java
> 
>   @Test
>   public void testExtraFields_valueNull() {
> ```

When not obvious, adding the acceptance criteria in the test name would make tests clearer : testExtraFields_valueNull_allowed
___
*[endpoints-framework/src/test/java/com/google/api/server/spi/ServiceExceptionTest.java, line 60 at r1](https://reviewable.io/reviews/aodocs/endpoints-java/13#-LZ9AC7V4sDoDVneLSKy:-LZ9AC7V4sDoDVneLSKz:bb1j0gr) ([raw file](https://github.com/aodocs/endpoints-java/blob/2c102c362e04f4a0c94b1eead76b699c744de18c/endpoints-framework/src/test/java/com/google/api/server/spi/ServiceExceptionTest.java#L60)):*
> ```Java
> 
>   @Test
>   public void testExtraFields_overrideValue() {
> ```

testExtraFields_overrideValue_lastKept
___
*[endpoints-framework/src/test/java/com/google/api/server/spi/ServiceExceptionTest.java, line 70 at r1](https://reviewable.io/reviews/aodocs/endpoints-java/13#-LZ9AO4o7bJsQRW7uCkP:-LZ9AO4o7bJsQRW7uCkQ:bko97g3) ([raw file](https://github.com/aodocs/endpoints-java/blob/2c102c362e04f4a0c94b1eead76b699c744de18c/endpoints-framework/src/test/java/com/google/api/server/spi/ServiceExceptionTest.java#L70)):*
> ```Java
> 
>   @Test
>   public void testExtraFields_ReservedDomain() {
> ```

testExtraFields_ReservedDomain_forbidden
___
*[endpoints-framework/src/test/java/com/google/api/server/spi/ServiceExceptionTest.java, line 75 at r1](https://reviewable.io/reviews/aodocs/endpoints-java/13#-LZ9APt82Z_Mmo5idDn8:-LZ9APt82Z_Mmo5idDn9:bsszvw) ([raw file](https://github.com/aodocs/endpoints-java/blob/2c102c362e04f4a0c94b1eead76b699c744de18c/endpoints-framework/src/test/java/com/google/api/server/spi/ServiceExceptionTest.java#L75)):*
> ```Java
> 
>   @Test
>   public void testExtraFields_ReservedMessage() {
> ```

testExtraFields_ReservedMessage_forbidden
___
*[endpoints-framework/src/test/java/com/google/api/server/spi/ServiceExceptionTest.java, line 80 at r1](https://reviewable.io/reviews/aodocs/endpoints-java/13#-LZ9ARwO2k7wFdfzesKj:-LZ9ARwO2k7wFdfzesKk:by3kl83) ([raw file](https://github.com/aodocs/endpoints-java/blob/2c102c362e04f4a0c94b1eead76b699c744de18c/endpoints-framework/src/test/java/com/google/api/server/spi/ServiceExceptionTest.java#L80)):*
> ```Java
> 
>   @Test
>   public void testExtraFields_ReservedReason() {
> ```

testExtraFields_ReservedReason_forbidden
___
*[endpoints-framework/src/test/java/com/google/api/server/spi/ServiceExceptionTest.java, line 84 at r1](https://reviewable.io/reviews/aodocs/endpoints-java/13#-LZ9AVuE-t_4E9ULxMJS:-LZ9AVuE-t_4E9ULxMJT:bynacar) ([raw file](https://github.com/aodocs/endpoints-java/blob/2c102c362e04f4a0c94b1eead76b699c744de18c/endpoints-framework/src/test/java/com/google/api/server/spi/ServiceExceptionTest.java#L84)):*
> ```Java
>   }
> 
>   public void testExtraFields_ReservedKeyword(String keyword) {
> ```

assertForbiddenExtraFieldName


<!-- Sent from Reviewable.io -->

2019-02-21 16:38 UTC, llbrt reviewed
> *[Reviewable](https://reviewable.io/reviews/aodocs/endpoints-java/13)* status: 3 of 6 files reviewed, 7 unresolved discussions (waiting on @alarribeau, @clementdenis, and @RaHery)

___
*[endpoints-framework/src/test/java/com/google/api/server/spi/ServiceExceptionTest.java, line 37 at r1](https://reviewable.io/reviews/aodocs/endpoints-java/13#-LZ99K5o9TPGPFtXJSNc:-LZFuxxsBxpEmzKyg--7:b-896fix) ([raw file](https://github.com/aodocs/endpoints-java/blob/2c102c362e04f4a0c94b1eead76b699c744de18c/endpoints-framework/src/test/java/com/google/api/server/spi/ServiceExceptionTest.java#L37)):*
<details><summary><i>Previously, alarribeau wrote…</i></summary><blockquote>

One addition by line would increase the readability and make the arrange bloc symmetric with the assertion bloc.
</blockquote></details>

Done.
___
*[endpoints-framework/src/test/java/com/google/api/server/spi/ServiceExceptionTest.java, line 51 at r1](https://reviewable.io/reviews/aodocs/endpoints-java/13#-LZ99vjpDvFN-yXaxdsZ:-LZFuyUj6IwbXBALRSPi:b-896fix) ([raw file](https://github.com/aodocs/endpoints-java/blob/2c102c362e04f4a0c94b1eead76b699c744de18c/endpoints-framework/src/test/java/com/google/api/server/spi/ServiceExceptionTest.java#L51)):*
<details><summary><i>Previously, alarribeau wrote…</i></summary><blockquote>

When not obvious, adding the acceptance criteria in the test name would make tests clearer : testExtraFields_valueNull_allowed
</blockquote></details>

Done.
___
*[endpoints-framework/src/test/java/com/google/api/server/spi/ServiceExceptionTest.java, line 60 at r1](https://reviewable.io/reviews/aodocs/endpoints-java/13#-LZ9AC7V4sDoDVneLSKy:-LZFuz9j-WHIyyE7YaJR:b-896fix) ([raw file](https://github.com/aodocs/endpoints-java/blob/2c102c362e04f4a0c94b1eead76b699c744de18c/endpoints-framework/src/test/java/com/google/api/server/spi/ServiceExceptionTest.java#L60)):*
<details><summary><i>Previously, alarribeau wrote…</i></summary><blockquote>

testExtraFields_overrideValue_lastKept
</blockquote></details>

Done.
___
*[endpoints-framework/src/test/java/com/google/api/server/spi/ServiceExceptionTest.java, line 70 at r1](https://reviewable.io/reviews/aodocs/endpoints-java/13#-LZ9AO4o7bJsQRW7uCkP:-LZFuzea-PG43vku9eTw:b-896fix) ([raw file](https://github.com/aodocs/endpoints-java/blob/2c102c362e04f4a0c94b1eead76b699c744de18c/endpoints-framework/src/test/java/com/google/api/server/spi/ServiceExceptionTest.java#L70)):*
<details><summary><i>Previously, alarribeau wrote…</i></summary><blockquote>

testExtraFields_ReservedDomain_forbidden
</blockquote></details>

Done.
___
*[endpoints-framework/src/test/java/com/google/api/server/spi/ServiceExceptionTest.java, line 75 at r1](https://reviewable.io/reviews/aodocs/endpoints-java/13#-LZ9APt82Z_Mmo5idDn8:-LZFv-6a0tCWV4MIr5aw:b-896fix) ([raw file](https://github.com/aodocs/endpoints-java/blob/2c102c362e04f4a0c94b1eead76b699c744de18c/endpoints-framework/src/test/java/com/google/api/server/spi/ServiceExceptionTest.java#L75)):*
<details><summary><i>Previously, alarribeau wrote…</i></summary><blockquote>

testExtraFields_ReservedMessage_forbidden
</blockquote></details>

Done.
___
*[endpoints-framework/src/test/java/com/google/api/server/spi/ServiceExceptionTest.java, line 80 at r1](https://reviewable.io/reviews/aodocs/endpoints-java/13#-LZ9ARwO2k7wFdfzesKj:-LZFv-aK4pmn89s7KeAM:b-896fix) ([raw file](https://github.com/aodocs/endpoints-java/blob/2c102c362e04f4a0c94b1eead76b699c744de18c/endpoints-framework/src/test/java/com/google/api/server/spi/ServiceExceptionTest.java#L80)):*
<details><summary><i>Previously, alarribeau wrote…</i></summary><blockquote>

testExtraFields_ReservedReason_forbidden
</blockquote></details>

Done.
___
*[endpoints-framework/src/test/java/com/google/api/server/spi/ServiceExceptionTest.java, line 84 at r1](https://reviewable.io/reviews/aodocs/endpoints-java/13#-LZ9AVuE-t_4E9ULxMJS:-LZFv-ua7sQdBpWW5dxj:b-896fix) ([raw file](https://github.com/aodocs/endpoints-java/blob/2c102c362e04f4a0c94b1eead76b699c744de18c/endpoints-framework/src/test/java/com/google/api/server/spi/ServiceExceptionTest.java#L84)):*
<details><summary><i>Previously, alarribeau wrote…</i></summary><blockquote>

assertForbiddenExtraFieldName
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2019-02-22 08:51 UTC, alarribeau approved these changes
> Reviewed 3 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/aodocs/endpoints-java/13)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @clementdenis and @RaHery)



<!-- Sent from Reviewable.io -->

2019-02-22 17:40 UTC, alarribeau approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/aodocs/endpoints-java/13#-:-LZLHi9WD6HwhpRq4W4y:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @clementdenis and @RaHery)



<!-- Sent from Reviewable.io -->

2019-02-25 07:53 UTC, clementdenis requested changes

2019-02-25 07:53 UTC, clementdenis commented on endpoints-framework/src/main/java/com/google/api/server/spi/ServiceException.java
> +  @Nonnull
I would not put @Nonnull here, as it's not used anywhere in the framework.
But I would add Javadoc with a note about nullity.

2019-02-25 07:53 UTC, clementdenis commented on endpoints-framework/src/main/java/com/google/api/server/spi/ServiceException.java
> +   * @throws IllegalArgumentException if {@code key} is one of the reserved keyword {@link #EXTRA_FIELDS_RESERVED_KEYWORDS}.
Add @throws NullPointerException on null key (same for the others)

2019-02-25 07:53 UTC, clementdenis commented on endpoints-framework/build.gradle
> +  testCompile group: 'org.skyscreamer', name: 'jsonassert', version: jsonassertVersion
Check license

2019-02-25 07:58 UTC, llbrt commented
___
*[endpoints-framework/build.gradle, line 113 at r2](https://reviewable.io/reviews/aodocs/endpoints-java/13#-LYk9zU9iNcZSY03luJ3-r2-113:-LZYdxZk34uBtz7v_IpA:b-w5gqvr) ([raw file](https://github.com/aodocs/endpoints-java/blob/175d655014ec2b6d7dc672fb23cc9ebd64dd3557/endpoints-framework/build.gradle#L113)):*
<details><summary><i>Previously, clementdenis (Clément Denis) wrote…</i></summary><blockquote>

Check license
</blockquote></details>

License Apache 2.0, the same one (see https://github.com/skyscreamer/JSONassert)


<!-- Sent from Reviewable.io -->

2019-02-25 09:48 UTC, llbrt reviewed
> *[Reviewable](https://reviewable.io/reviews/aodocs/endpoints-java/13)* status: all files reviewed, 3 unresolved discussions (waiting on @clementdenis and @RaHery)

___
*[endpoints-framework/build.gradle, line 113 at r2](https://reviewable.io/reviews/aodocs/endpoints-java/13#-LYk9zU9iNcZSY03luJ3-r2-113:-LZZ1hFA-ky_M8J7ZlOZ:b-xs0yoh) ([raw file](https://github.com/aodocs/endpoints-java/blob/175d655014ec2b6d7dc672fb23cc9ebd64dd3557/endpoints-framework/build.gradle#L113)):*
<details><summary><i>Previously, llbrt (Loïc Lambert) wrote…</i></summary><blockquote>

License Apache 2.0, the same one (see https://github.com/skyscreamer/JSONassert)
</blockquote></details>

Done. Will add a line on the dependency in the definite commit log (after squash).
___
*[endpoints-framework/src/main/java/com/google/api/server/spi/ServiceException.java, line 121 at r2](https://reviewable.io/reviews/aodocs/endpoints-java/13#-LYk9zU9iNcZSY03luJ4-r2-121:-LZZ1jWABqxbQ2n2A881:b-jek0bv) ([raw file](https://github.com/aodocs/endpoints-java/blob/175d655014ec2b6d7dc672fb23cc9ebd64dd3557/endpoints-framework/src/main/java/com/google/api/server/spi/ServiceException.java#L121)):*
<details><summary><i>Previously, clementdenis (Clément Denis) wrote…</i></summary><blockquote>

Add @throws NullPointerException on null key (same for the others)
</blockquote></details>

Done.
Refactor addExtraField => putExtraField as the contract is a map-like contract. A method 'add' may create a list of values, instead of keeping the last one.
___
*[endpoints-framework/src/main/java/com/google/api/server/spi/ServiceException.java, line 156 at r2](https://reviewable.io/reviews/aodocs/endpoints-java/13#-LYk9zU9iNcZSY03luJ4-r2-156:-LZZ21UjAPeb-hgoAXbd:b-okxo09) ([raw file](https://github.com/aodocs/endpoints-java/blob/175d655014ec2b6d7dc672fb23cc9ebd64dd3557/endpoints-framework/src/main/java/com/google/api/server/spi/ServiceException.java#L156)):*
<details><summary><i>Previously, clementdenis (Clément Denis) wrote…</i></summary><blockquote>

I would not put @Nonnull here, as it's not used anywhere in the framework.
But I would add Javadoc with a note about nullity.
</blockquote></details>

Missing Javadoc added.


<!-- Sent from Reviewable.io -->

2019-02-26 14:24 UTC, alarribeau approved these changes
> Reviewed 3 of 3 files at r3.
> *[Reviewable](https://reviewable.io/reviews/aodocs/endpoints-java/13)* status: all files reviewed, 3 unresolved discussions (waiting on @clementdenis and @RaHery)



<!-- Sent from Reviewable.io -->

2019-02-26 14:49 UTC, clementdenis requested changes
Some naming and formatting details to address

2019-02-26 14:49 UTC, clementdenis commented on endpoints-framework/src/main/java/com/google/api/server/spi/ServiceException.java
> +  private static final FluentLogger logger = FluentLogger.forEnclosingClass();
Missing newline after class declaration (Google is picky on formatting)

2019-02-26 14:49 UTC, clementdenis commented on endpoints-framework/src/main/java/com/google/api/server/spi/ServiceException.java
> +    Preconditions.checkArgument(!EXTRA_FIELDS_RESERVED_KEYWORDS.contains(key), "The keyword '%s' is reserved", key);
The keyword '%s' is reserved => The field name '%s' is reserved

2019-02-26 14:49 UTC, clementdenis commented on endpoints-framework/src/main/java/com/google/api/server/spi/ServiceException.java
> +  public ServiceException putExtraField(String key, String value) {
Shouldn't we use fieldName instead of key as the first arg name?

2019-02-26 14:49 UTC, clementdenis commented on endpoints-framework/src/main/java/com/google/api/server/spi/ServiceException.java
> +    return Collections.unmodifiableMap(extraFields);
I would rather use a Guava's ImmutableMap, and return the type explicitly.

2019-02-27 09:38 UTC, llbrt reviewed
> *[Reviewable](https://reviewable.io/reviews/aodocs/endpoints-java/13)* status: 4 of 6 files reviewed, 7 unresolved discussions (waiting on @alarribeau, @clementdenis, and @RaHery)

___
*[endpoints-framework/src/main/java/com/google/api/server/spi/ServiceException.java, line 33 at r3](https://reviewable.io/reviews/aodocs/endpoints-java/13#-LYk9zU9iNcZSY03luJ4-r3-33:-LZhyStQBqrUuXbt253t:b-896fix) ([raw file](https://github.com/aodocs/endpoints-java/blob/6506b7a973a0cc07f999dec201e9272254c706c0/endpoints-framework/src/main/java/com/google/api/server/spi/ServiceException.java#L33)):*
<details><summary><i>Previously, clementdenis (Clément Denis) wrote…</i></summary><blockquote>

Missing newline after class declaration (Google is picky on formatting)
</blockquote></details>

Done.
___
*[endpoints-framework/src/main/java/com/google/api/server/spi/ServiceException.java, line 124 at r3](https://reviewable.io/reviews/aodocs/endpoints-java/13#-LYk9zU9iNcZSY03luJ4-r3-124:-LZhyVsO4ZvW922nCb1G:b7dqjwj) ([raw file](https://github.com/aodocs/endpoints-java/blob/6506b7a973a0cc07f999dec201e9272254c706c0/endpoints-framework/src/main/java/com/google/api/server/spi/ServiceException.java#L124)):*
<details><summary><i>Previously, clementdenis (Clément Denis) wrote…</i></summary><blockquote>

Shouldn't we use fieldName instead of key as the first arg name?
</blockquote></details>

Yes, it's better
___
*[endpoints-framework/src/main/java/com/google/api/server/spi/ServiceException.java, line 154 at r3](https://reviewable.io/reviews/aodocs/endpoints-java/13#-LYk9zU9iNcZSY03luJ4-r3-154:-LZhya525SGQYtQjGOo_:b-896fix) ([raw file](https://github.com/aodocs/endpoints-java/blob/6506b7a973a0cc07f999dec201e9272254c706c0/endpoints-framework/src/main/java/com/google/api/server/spi/ServiceException.java#L154)):*
<details><summary><i>Previously, clementdenis (Clément Denis) wrote…</i></summary><blockquote>

The keyword '%s' is reserved => The field name '%s' is reserved
</blockquote></details>

Done.
___
*[endpoints-framework/src/main/java/com/google/api/server/spi/ServiceException.java, line 168 at r3](https://reviewable.io/reviews/aodocs/endpoints-java/13#-LYk9zU9iNcZSY03luJ4-r3-168:-LZhycz29TF5pjxfOZJQ:b9x7bpk) ([raw file](https://github.com/aodocs/endpoints-java/blob/6506b7a973a0cc07f999dec201e9272254c706c0/endpoints-framework/src/main/java/com/google/api/server/spi/ServiceException.java#L168)):*
<details><summary><i>Previously, clementdenis (Clément Denis) wrote…</i></summary><blockquote>

I would rather use a Guava's ImmutableMap, and return the type explicitly.
</blockquote></details>

As discussed, this would better document immutability.
Unfortunately ImmutableMap does not accept a null value and I think the framework should accept a field with a null value rather than throwing an exception or ignoring it (even if there is a log).
Maybe the error occurred because some value is null somewhere and that value is added as a field in the exception in a class catching internal exceptions.


<!-- Sent from Reviewable.io -->

2019-02-27 09:41 UTC, alarribeau approved these changes
> Reviewed 2 of 2 files at r4.
> *[Reviewable](https://reviewable.io/reviews/aodocs/endpoints-java/13)* status: all files reviewed, 7 unresolved discussions (waiting on @clementdenis and @RaHery)



<!-- Sent from Reviewable.io -->

2019-02-28 10:26 UTC, llbrt reviewed
> *[Reviewable](https://reviewable.io/reviews/aodocs/endpoints-java/13)* status: all files reviewed, 7 unresolved discussions (waiting on @clementdenis and @RaHery)

___
*[endpoints-framework/src/main/java/com/google/api/server/spi/ServiceException.java, line 168 at r3](https://reviewable.io/reviews/aodocs/endpoints-java/13#-LYk9zU9iNcZSY03luJ4-r3-168:-LZncvd34YTjeqIu5q0R:b-896fix) ([raw file](https://github.com/aodocs/endpoints-java/blob/6506b7a973a0cc07f999dec201e9272254c706c0/endpoints-framework/src/main/java/com/google/api/server/spi/ServiceException.java#L168)):*
<details><summary><i>Previously, llbrt (Loïc Lambert) wrote…</i></summary><blockquote>

As discussed, this would better document immutability.
Unfortunately ImmutableMap does not accept a null value and I think the framework should accept a field with a null value rather than throwing an exception or ignoring it (even if there is a log).
Maybe the error occurred because some value is null somewhere and that value is added as a field in the exception in a class catching internal exceptions.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2019-02-28 14:21 UTC, alarribeau approved these changes
> Reviewed 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/aodocs/endpoints-java/13)* status: all files reviewed, 7 unresolved discussions (waiting on @clementdenis and @RaHery)



<!-- Sent from Reviewable.io -->

2019-03-27 08:32 UTC, llbrt commented
Committed with a wrong email address: I close this one and create a new one with the right email address.

2019-03-27 08:32 UTC, closed without merging