Replace API explorer with developers.google.com
AODocs/endpoints-java pull request #17
Opened 2019-03-21 23:09 UTC by clementdenis

2019-03-22 21:01 UTC, alarribeau approved these changes

2019-03-27 08:54 UTC, llbrt requested changes
> Reviewed 3 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/aodocs/endpoints-java/17)* status: all files reviewed, 1 unresolved discussion (waiting on @clementdenis and @RaHery)

___
*[endpoints-framework/src/main/java/com/google/api/server/spi/handlers/ExplorerHandler.java, line 41 at r1](https://reviewable.io/reviews/aodocs/endpoints-java/17#-LayL7Wk0Qvzrf1MC4WZ:-LayL7Wk0Qvzrf1MC4W_:bx2magu) ([raw file](https://github.com/aodocs/endpoints-java/blob/2fc26101cf8d8dccd336999f5760d1078b70d9f4/endpoints-framework/src/main/java/com/google/api/server/spi/handlers/ExplorerHandler.java#L41)):*
> ```Java
>     String url = stripRedundantPorts(Strings.stripTrailingSlash(req.getRequestURL().toString()));
>     // This will convert http://localhost:8080/_ah/api/explorer to
>     // http://apis-explorer.appspot.com/apis-explorer/?base=http://localhost:8080/_ah/api&
> ```

Still a reference on http://apis-explorer.appspot in this comment


<!-- Sent from Reviewable.io -->

2019-04-01 13:59 UTC, RaHery approved these changes

2019-04-10 10:20 UTC, llbrt approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/aodocs/endpoints-java/17#-:-Lc5koMGAQwMyO7tLQgZ:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @clementdenis)



<!-- Sent from Reviewable.io -->

2019-04-10 11:47 UTC, merged