Request parameters validation (#58)
AODocs/endpoints-java pull request #59
Opened 2021-10-28 16:50 UTC by alarribeau

- Supports request parameters validation through standard Java bean validation
- Validation can be turned off with a servlet parameter : `enableParameterValidation`

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aodocs/endpoints-java/59)

2021-10-29 13:15 UTC, clementdenis requested changes
> Reviewed 12 of 12 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/aodocs/endpoints-java/59)* status: all files reviewed, 9 unresolved discussions (waiting on @alarribeau)

___
*[README.md, line 35 at r1](https://reviewable.io/reviews/aodocs/endpoints-java/59#-MnB5V9P14OvUCBkMHFb:-MnB5V9P14OvUCBkMHFc:b-zc4hk1) ([raw file](https://github.com/aodocs/endpoints-java/blob/4509ed86e94525f434d620926b85e6e1ef6f7d0a/README.md#L35)):*
> ```
> Validate request parameters through
> ```

"Validate request parameters and body through" ?
___
*[endpoints-framework/build.gradle, line 106 at r1](https://reviewable.io/reviews/aodocs/endpoints-java/59#-MnB71XqCAaz36Nvp8Iv:-MnB71XqCAaz36Nvp8Iw:bywc60n) ([raw file](https://github.com/aodocs/endpoints-java/blob/4509ed86e94525f434d620926b85e6e1ef6f7d0a/endpoints-framework/build.gradle#L106)):*
> ```Gradle
> 
>   api group: 'org.hibernate.validator', name: 'hibernate-validator', version: hibernateValidatorVersion
>   api group: 'javax.validation', name: 'validation-api', version: validationApiVersion
> ```

The classpath of the project also contains jakarta.validation-api-2.0.2.jar, which seems to be mostly the same as this one.
Shouldn't we have only one of them?
___
*[endpoints-framework/src/main/java/com/google/api/server/spi/ServletInitializationParameters.java, line 45 at r1](https://reviewable.io/reviews/aodocs/endpoints-java/59#-MnB7Fy93GWuur3Ej0p_:-MnB7Fy93GWuur3Ej0pa:b-dc73ht) ([raw file](https://github.com/aodocs/endpoints-java/blob/4509ed86e94525f434d620926b85e6e1ef6f7d0a/endpoints-framework/src/main/java/com/google/api/server/spi/ServletInitializationParameters.java#L45)):*
> ```Java
>   private static final String ADD_CONTENT_LENGTH = "addContentLength";
>   private static final String API_EXPLORER_URL_TEMPLATE = "apiExplorerUrlTemplate";
>   private static final String PARAMETER_VALIDATION = "enableParameterValidation";
> ```

Couldn't this be just "enableValidation" (same for the naming of the other variables)
=> From a Java perspective, we are indeed validating parameters, but on the REST level we're validation the parameters and the body.
___
*[endpoints-framework/src/main/java/com/google/api/server/spi/handlers/EndpointsMethodHandler.java, line 89 at r1](https://reviewable.io/reviews/aodocs/endpoints-java/59#-MnB7ZBIEdpaOyPZPQuL:-MnB7ZBIEdpaOyPZPQuM:bduxlg) ([raw file](https://github.com/aodocs/endpoints-java/blob/4509ed86e94525f434d620926b85e6e1ef6f7d0a/endpoints-framework/src/main/java/com/google/api/server/spi/handlers/EndpointsMethodHandler.java#L89)):*
> ```Java
>   @VisibleForTesting
>   protected ParamReader createRestParamReader(EndpointsContext context,
>       ApiSerializationConfig serializationConfig, Object service) {
> ```

Can you rename service to apiService? It would be a bit more explicit ...
___
*[endpoints-framework/src/main/java/com/google/api/server/spi/request/AbstractParamReader.java, line 24 at r1](https://reviewable.io/reviews/aodocs/endpoints-java/59#-MnB56iW92pordh9lyGs:-MnB56iXC3z-bP2sksJs:byy477v) ([raw file](https://github.com/aodocs/endpoints-java/blob/4509ed86e94525f434d620926b85e6e1ef6f7d0a/endpoints-framework/src/main/java/com/google/api/server/spi/request/AbstractParamReader.java#L24)):*
> ```Java
>  */
> public abstract class AbstractParamReader implements ParamReader {
>   private final Object service;
> ```

Why are you storing "service" in AbstractParamReader?
It's only used in the subclass ServletRequestParamReader
___
*[endpoints-framework/src/main/java/com/google/api/server/spi/request/ServletRequestParamReader.java, line 90 at r1](https://reviewable.io/reviews/aodocs/endpoints-java/59#-MnB8rxh3lubwjtvA8jP:-MnB8rxh3lubwjtvA8jQ:bp4xisf) ([raw file](https://github.com/aodocs/endpoints-java/blob/4509ed86e94525f434d620926b85e6e1ef6f7d0a/endpoints-framework/src/main/java/com/google/api/server/spi/request/ServletRequestParamReader.java#L90)):*
> ```Java
>   private static final Validator VALIDATOR = Validation.byDefaultProvider()
>           .configure()
>           .messageInterpolator(new ParameterMessageInterpolator())
> ```

ParameterMessageInterpolator is the only explicit reference to Hibernate validator, so there's not much more to do to:
- Make the dependency to Hibernate validator optional
- Allow the library consumers to use their own validation library

=> Couldn't you instantiate this Validator in a static method, catching  the NoProviderFoundException in case there's no provider, and instantiate ParameterMessageInterpolator by reflection, possibly with a way to configure an alternate MessageInterpolator class?

If no validation impl is found in the classpath, the validation would just be disabled (maybe with a warning)
___
*[endpoints-framework/src/main/java/com/google/api/server/spi/request/ServletRequestParamReader.java, line 462 at r1](https://reviewable.io/reviews/aodocs/endpoints-java/59#-MnB61c6BwzIF4Di_CUa:-MnB61c6BwzIF4Di_CUb:boynjqk) ([raw file](https://github.com/aodocs/endpoints-java/blob/4509ed86e94525f434d620926b85e6e1ef6f7d0a/endpoints-framework/src/main/java/com/google/api/server/spi/request/ServletRequestParamReader.java#L462)):*
> ```Java
>   protected Object[] validateParameters(Object[] parameterValues) throws BadRequestException {
>     if (validationEnabled) {
>       Set<ConstraintViolation<Object>> constraintViolations = VALIDATOR.forExecutables().validateParameters(getService(), getMethod().getMethod(), parameterValues);
> ```

Is it really that magical? This will validate both the annotated path/query params AND the request body object?
___
*[endpoints-framework/src/main/java/com/google/api/server/spi/request/ServletRequestParamReader.java, line 468 at r1](https://reviewable.io/reviews/aodocs/endpoints-java/59#-MnB4kD4160DtUttAhwX:-MnB4kD4160DtUttAhwY:b-xvr80c) ([raw file](https://github.com/aodocs/endpoints-java/blob/4509ed86e94525f434d620926b85e6e1ef6f7d0a/endpoints-framework/src/main/java/com/google/api/server/spi/request/ServletRequestParamReader.java#L468)):*
> ```Java
>           String error = violation.getPropertyPath().toString() + " " + violation.getMessage();
>           errors.add(error);
>         }
> ```

Would be nicer using a stream()
___
*[endpoints-framework/src/main/java/com/google/api/server/spi/request/ServletRequestParamReader.java, line 469 at r1](https://reviewable.io/reviews/aodocs/endpoints-java/59#-MnB4cTM1xZwgEA6BcsG:-MnB4cTM1xZwgEA6BcsH:b-1i3ljb) ([raw file](https://github.com/aodocs/endpoints-java/blob/4509ed86e94525f434d620926b85e6e1ef6f7d0a/endpoints-framework/src/main/java/com/google/api/server/spi/request/ServletRequestParamReader.java#L469)):*
> ```
> Invalid parameters :
> ```
Remove space before :
___
*[endpoints-framework/src/test/java/com/google/api/server/spi/request/ServletRequestParamReaderTest.java, line 855 at r1](https://reviewable.io/reviews/aodocs/endpoints-java/59#-MnB6XsB7vX5F1MAW-QQ:-MnB6XsB7vX5F1MAW-QR:b-lhcqbl) ([raw file](https://github.com/aodocs/endpoints-java/blob/4509ed86e94525f434d620926b85e6e1ef6f7d0a/endpoints-framework/src/test/java/com/google/api/server/spi/request/ServletRequestParamReaderTest.java#L855)):*
> ```Java
>           methodConfig,
>           null,
>           null, 
> ```

Two useless spaces after the ,
___
*[endpoints-framework/src/test/java/com/google/api/server/spi/request/ServletRequestParamReaderTest.java, line 916 at r1](https://reviewable.io/reviews/aodocs/endpoints-java/59#-MnBA_RR5Z0wAncIqTdj:-MnBA_RR5Z0wAncIqTdk:b-5dw199) ([raw file](https://github.com/aodocs/endpoints-java/blob/4509ed86e94525f434d620926b85e6e1ef6f7d0a/endpoints-framework/src/test/java/com/google/api/server/spi/request/ServletRequestParamReaderTest.java#L916)):*
> ```Java
>       fail("expected bad request exception");
>     } catch (BadRequestException ex) {
>       assertTrue("failed for unexpected reason: " + ex.getMessage(), ex.getMessage().contains("test.testParam must match"));
> ```

Is the "test." prefix mandatory?
Is it the Java method nam [...]

2021-10-29 15:37 UTC, alarribeau reviewed
> *[Reviewable](https://reviewable.io/reviews/aodocs/endpoints-java/59)* status: all files reviewed, 10 unresolved discussions (waiting on @alarribeau and @clementdenis)

___
*[README.md, line 35 at r1](https://reviewable.io/reviews/aodocs/endpoints-java/59#-MnB5V9P14OvUCBkMHFb:-MnBVnYjBwutOySQz63O:b-ynvt21) ([raw file](https://github.com/aodocs/endpoints-java/blob/4509ed86e94525f434d620926b85e6e1ef6f7d0a/README.md#L35)):*
<details><summary><i>Previously, clementdenis (Clément Denis) wrote…</i></summary><blockquote>

> ```
> Validate request parameters through
> ```

"Validate request parameters and body through" ?
</blockquote></details>

In my personal terminology I consider that there are 3 main kinds of request parameters : 
- query parameters
- path parameters
- resource/body parameter

But of course I'm ok with your suggestion :) 
___
*[endpoints-framework/build.gradle, line 106 at r1](https://reviewable.io/reviews/aodocs/endpoints-java/59#-MnB71XqCAaz36Nvp8Iv:-MnBZjDx-kRwXF9gFumk:b37jd0c) ([raw file](https://github.com/aodocs/endpoints-java/blob/4509ed86e94525f434d620926b85e6e1ef6f7d0a/endpoints-framework/build.gradle#L106)):*
<details><summary><i>Previously, clementdenis (Clément Denis) wrote…</i></summary><blockquote>

The classpath of the project also contains jakarta.validation-api-2.0.2.jar, which seems to be mostly the same as this one.
Shouldn't we have only one of them?
</blockquote></details>

Yes probably, I thought that the jakarta version had the jakarta package already. 

I probably I misread this article : 
https://in.relation.to/2021/01/06/hibernate-validator-700-62-final-released/
___
*[endpoints-framework/src/main/java/com/google/api/server/spi/ServletInitializationParameters.java, line 45 at r1](https://reviewable.io/reviews/aodocs/endpoints-java/59#-MnB7Fy93GWuur3Ej0p_:-MnB_Orw2eGdAYETC-0E:bu860vk) ([raw file](https://github.com/aodocs/endpoints-java/blob/4509ed86e94525f434d620926b85e6e1ef6f7d0a/endpoints-framework/src/main/java/com/google/api/server/spi/ServletInitializationParameters.java#L45)):*
<details><summary><i>Previously, clementdenis (Clément Denis) wrote…</i></summary><blockquote>

Couldn't this be just "enableValidation" (same for the naming of the other variables)
=> From a Java perspective, we are indeed validating parameters, but on the REST level we're validation the parameters and the body.
</blockquote></details>

Cf to my previous comment.

Maybe : `enableInputValidation` ?
___
*[endpoints-framework/src/main/java/com/google/api/server/spi/handlers/EndpointsMethodHandler.java, line 89 at r1](https://reviewable.io/reviews/aodocs/endpoints-java/59#-MnB7ZBIEdpaOyPZPQuL:-MnB_inh-Wi0cZtEOoI_:bb74ce2) ([raw file](https://github.com/aodocs/endpoints-java/blob/4509ed86e94525f434d620926b85e6e1ef6f7d0a/endpoints-framework/src/main/java/com/google/api/server/spi/handlers/EndpointsMethodHandler.java#L89)):*
<details><summary><i>Previously, clementdenis (Clément Denis) wrote…</i></summary><blockquote>

Can you rename service to apiService? It would be a bit more explicit ...
</blockquote></details>

Sure
___
*[endpoints-framework/src/main/java/com/google/api/server/spi/request/AbstractParamReader.java, line 24 at r1](https://reviewable.io/reviews/aodocs/endpoints-java/59#-MnB56iW92pordh9lyGs:-MnBaDiQCzqFmb__QCB0:b-7bw56z) ([raw file](https://github.com/aodocs/endpoints-java/blob/4509ed86e94525f434d620926b85e6e1ef6f7d0a/endpoints-framework/src/main/java/com/google/api/server/spi/request/AbstractParamReader.java#L24)):*
<details><summary><i>Previously, clementdenis (Clément Denis) wrote…</i></summary><blockquote>

Why are you storing "service" in AbstractParamReader?
It's only used in the subclass ServletRequestParamReader
</blockquote></details>

I stored it here because it felt "right" (coherent) to store the service along with the method. But I don't mind moving it if you think it is better.

Btw, your remark could also be applied to the method :smile:  this class hierarchy is dubious...
___
*[endpoints-framework/src/main/java/com/google/api/server/spi/request/ServletRequestParamReader.java, line 90 at r1](https://reviewable.io/reviews/aodocs/endpoints-java/59#-MnB8rxh3lubwjtvA8jP:-MnBbZkA9nidkJof2Xw-:b-xbvofd) ([raw file](https://github.com/aodocs/endpoints-java/blob/4509ed86e94525f434d620926b85e6e1ef6f7d0a/endpoints-framework/src/main/java/com/google/api/server/spi/request/ServletRequestParamReader.java#L90)):*
<details><summary><i>Previously, clementdenis (Clément Denis) wrote…</i></summary><blockquote>

ParameterMessageInterpolator is the only explicit reference to Hibernate validator, so there's not much more to do to:
- Make the dependency to Hibernate validator optional
- Allow the library consumers to use their own validation library

=> Couldn't you instantiate this Validator in a static method, catching  the NoProviderFoundException in case there's no provider, and instantiate ParameterMessageInterpolator by reflection, possibly with a way to configure an alternate MessageInterpolator class?

If no validation impl is found in the classpath, the validation would just be disabled (maybe with a warning)
</blockquote></details>

Interesting idea (to make the dependence optional).

Btw, I was reluctant to use this message interpolator implementation in the first place.

If we offer a way to provide/tune a custom validator I wouldn't even bother trying to instantiate this particular interpolator by reflection.
___
*[endpoints-framework/src/main/java/com/google/api/server/spi/request/ServletRequestParamReader.java, line 462 at r1](https://reviewable.io/reviews/aodocs/endpoints-java/59#-MnB61c6BwzIF4Di_CUa:-MnBcjXBCcei8QkuatJC:b-x871za) ([raw file](https://github.com/aodocs/endpoints-java/blob/4509ed86e94525f434d620926b85e6e1ef6f7d0a/endpoints-framework/src/main/java/com/google/api/server/spi/request/ServletRequestParamReader.java#L462)):*
<details><summary><i>Previously, clementdenis (Clément Denis) wrote…</i></summary><blockquote>

Is it really that magical? This will validate both the annotated path/query params AND the request body object?
</blockquote></details>

Yes as long as it is annotated with the @Valid annotation (there's a test).

The reason is that body/resource params are also declared in the API method, they are considered as a special kind of parameter. 
___
*[endpoints-framework/src/main/java/com/google/api/server/spi/request/ServletRequestParamReader.java, line 468 at r1](https://reviewable.io/reviews/aodocs/endpoints-java/59#-MnB4kD4160DtUttAhwX:-MnBdBPl4K1HYC_scrnX:b96gt8x) ([raw file](https://github.com/aodocs/endpoints-java/blob/4509ed86e94525f434d620926b85e6e1ef6f7d0a/endpoints-framework/src/main/java/com/google/api/server/spi/request/ServletRequestParamReader.java#L468)):*
<details><summary><i>Previously, clementdenis (Clément Denis) wrote…</i></summary><blockquote>

Would be nicer using a stream()
</blockquote></details>

Indeed, I copied this, shame on me :monkey_face: 
___
*[endpoints-framework/src/test/java/com/google/api/server/spi/request/ServletRequestParamReaderTest.java, line 916 at r1](https://reviewable.io/reviews/aodocs/endpoints-java/59#-MnBA_RR5Z0wAncIqTdj:-MnBdXCB2r7xDQZl4WiP:brnrk5e) ([raw file](https://github.com/aodocs/endpoints-java/blob/4509ed86e94525f434d620926b85e6e1ef6f7d0a/endpoints-framework/src/test/java/com/google/api/server/spi/request/ServletRequestParamReaderTest.java#L916)):*
<details><summary><i>Previously, clementdenis (Clément Denis) wrote…</i></summary><blockquote>

Is the "test." prefix mandatory?
Is it the Java method name, or the name of the API method (which can be overridden from the Java name).
 
</blockquote></details>

Good point, I think it is the java method name.  But it should be easy to use the API name by  postprocessing the violation.getPropertyPath().
I'll look into it.
___
*[endpoints-framework/src/test/java/com/google/api/server/spi/request/ServletRequestParamReaderTest.java, line 950 at r1](https://reviewable.io/reviews/aodocs/endpoints- [...]

2021-10-29 16:27 UTC, alarribeau reviewed
> *[Reviewable](https://reviewable.io/reviews/aodocs/endpoints-java/59)* status: all files reviewed, 10 unresolved discussions (waiting on @alarribeau and @clementdenis)

___
*[endpoints-framework/build.gradle, line 106 at r1](https://reviewable.io/reviews/aodocs/endpoints-java/59#-MnB71XqCAaz36Nvp8Iv:-MnBrQ9B-4S6RJzZtZhm:bp19gjq) ([raw file](https://github.com/aodocs/endpoints-java/blob/4509ed86e94525f434d620926b85e6e1ef6f7d0a/endpoints-framework/build.gradle#L106)):*
<details><summary><i>Previously, alarribeau wrote…</i></summary><blockquote>

Yes probably, I thought that the jakarta version had the jakarta package already. 

I probably I misread this article : 
https://in.relation.to/2021/01/06/hibernate-validator-700-62-final-released/
</blockquote></details>

Actually : 
- swagger-core depends on javax.validation
- hibernate-validator depends on jakarta.validation

If hibernate-validator becames optional we could depend only on javax.validation.  Not sure about it....


<!-- Sent from Reviewable.io -->

2021-10-29 17:02 UTC, alarribeau reviewed
> *[Reviewable](https://reviewable.io/reviews/aodocs/endpoints-java/59)* status: 1 of 12 files reviewed, 8 unresolved discussions (waiting on @alarribeau and @clementdenis)

___
*[README.md, line 35 at r1](https://reviewable.io/reviews/aodocs/endpoints-java/59#-MnB5V9P14OvUCBkMHFb:-MnBzKlF7Jf3caN9ScxG:b-896fix) ([raw file](https://github.com/aodocs/endpoints-java/blob/4509ed86e94525f434d620926b85e6e1ef6f7d0a/README.md#L35)):*
<details><summary><i>Previously, alarribeau wrote…</i></summary><blockquote>

In my personal terminology I consider that there are 3 main kinds of request parameters : 
- query parameters
- path parameters
- resource/body parameter

But of course I'm ok with your suggestion :) 
</blockquote></details>

Done.
___
*[endpoints-framework/src/main/java/com/google/api/server/spi/ServletInitializationParameters.java, line 45 at r1](https://reviewable.io/reviews/aodocs/endpoints-java/59#-MnB7Fy93GWuur3Ej0p_:-MnBzHqN8lgfBArGGTMC:b-896fix) ([raw file](https://github.com/aodocs/endpoints-java/blob/4509ed86e94525f434d620926b85e6e1ef6f7d0a/endpoints-framework/src/main/java/com/google/api/server/spi/ServletInitializationParameters.java#L45)):*
<details><summary><i>Previously, alarribeau wrote…</i></summary><blockquote>

Cf to my previous comment.

Maybe : `enableInputValidation` ?
</blockquote></details>

Done.
___
*[endpoints-framework/src/main/java/com/google/api/server/spi/handlers/EndpointsMethodHandler.java, line 89 at r1](https://reviewable.io/reviews/aodocs/endpoints-java/59#-MnB7ZBIEdpaOyPZPQuL:-MnByi1gAZYuOi27OW5z:b-896fix) ([raw file](https://github.com/aodocs/endpoints-java/blob/4509ed86e94525f434d620926b85e6e1ef6f7d0a/endpoints-framework/src/main/java/com/google/api/server/spi/handlers/EndpointsMethodHandler.java#L89)):*
<details><summary><i>Previously, alarribeau wrote…</i></summary><blockquote>

Sure
</blockquote></details>

Done.
___
*[endpoints-framework/src/main/java/com/google/api/server/spi/request/ServletRequestParamReader.java, line 468 at r1](https://reviewable.io/reviews/aodocs/endpoints-java/59#-MnB4kD4160DtUttAhwX:-MnBu5CADzC3ZyZWATQN:bb6un1j) ([raw file](https://github.com/aodocs/endpoints-java/blob/4509ed86e94525f434d620926b85e6e1ef6f7d0a/endpoints-framework/src/main/java/com/google/api/server/spi/request/ServletRequestParamReader.java#L468)):*
<details><summary><i>Previously, alarribeau wrote…</i></summary><blockquote>

Indeed, I copied this, shame on me :monkey_face: 
</blockquote></details>

Done
___
*[endpoints-framework/src/main/java/com/google/api/server/spi/request/ServletRequestParamReader.java, line 469 at r1](https://reviewable.io/reviews/aodocs/endpoints-java/59#-MnB4cTM1xZwgEA6BcsG:-MnBu4943xyohcDifJn-:b-896fix) ([raw file](https://github.com/aodocs/endpoints-java/blob/4509ed86e94525f434d620926b85e6e1ef6f7d0a/endpoints-framework/src/main/java/com/google/api/server/spi/request/ServletRequestParamReader.java#L469)):*
<details><summary><i>Previously, clementdenis (Clément Denis) wrote…</i></summary><blockquote>

> ```
> Invalid parameters :
> ```
Remove space before :
</blockquote></details>

Done.
___
*[endpoints-framework/src/test/java/com/google/api/server/spi/request/ServletRequestParamReaderTest.java, line 916 at r1](https://reviewable.io/reviews/aodocs/endpoints-java/59#-MnBA_RR5Z0wAncIqTdj:-MnBuXKZ9gkY6I-c0qcF:b-um4i3x) ([raw file](https://github.com/aodocs/endpoints-java/blob/4509ed86e94525f434d620926b85e6e1ef6f7d0a/endpoints-framework/src/test/java/com/google/api/server/spi/request/ServletRequestParamReaderTest.java#L916)):*
<details><summary><i>Previously, alarribeau wrote…</i></summary><blockquote>

Good point, I think it is the java method name.  But it should be easy to use the API name by  postprocessing the violation.getPropertyPath().
I'll look into it.
</blockquote></details>

Actually it was even easier to get rid of the method name. I think it is useless.


<!-- Sent from Reviewable.io -->

2021-11-02 12:15 UTC, clementdenis requested changes
> Reviewed 11 of 11 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/aodocs/endpoints-java/59)* status: all files reviewed, 2 unresolved discussions (waiting on @alarribeau)

___
*[endpoints-framework/build.gradle, line 106 at r1](https://reviewable.io/reviews/aodocs/endpoints-java/59#-MnB71XqCAaz36Nvp8Iv:-MnVYzPo7v97zb6OZtDv:b-dkkipb) ([raw file](https://github.com/aodocs/endpoints-java/blob/4509ed86e94525f434d620926b85e6e1ef6f7d0a/endpoints-framework/build.gradle#L106)):*
<details><summary><i>Previously, alarribeau wrote…</i></summary><blockquote>

Actually : 
- swagger-core depends on javax.validation
- hibernate-validator depends on jakarta.validation

If hibernate-validator becames optional we could depend only on javax.validation.  Not sure about it....
</blockquote></details>

We should probably ignore javax.validation from swagger-core then ...
___
*[endpoints-framework/src/main/java/com/google/api/server/spi/request/AbstractParamReader.java, line 24 at r1](https://reviewable.io/reviews/aodocs/endpoints-java/59#-MnB56iW92pordh9lyGs:-MnVZHIIBprDUJgfrcta:b-6xjrvp) ([raw file](https://github.com/aodocs/endpoints-java/blob/4509ed86e94525f434d620926b85e6e1ef6f7d0a/endpoints-framework/src/main/java/com/google/api/server/spi/request/AbstractParamReader.java#L24)):*
<details><summary><i>Previously, alarribeau wrote…</i></summary><blockquote>

I stored it here because it felt "right" (coherent) to store the service along with the method. But I don't mind moving it if you think it is better.

Btw, your remark could also be applied to the method :smile:  this class hierarchy is dubious...
</blockquote></details>

Indeed, if we want to be consistant with the existing method object, we might as well keep it here. Fine for me then :)
___
*[endpoints-framework/src/main/java/com/google/api/server/spi/request/ServletRequestParamReader.java, line 90 at r1](https://reviewable.io/reviews/aodocs/endpoints-java/59#-MnB8rxh3lubwjtvA8jP:-MnVZq5aCIYVnPdXngBU:bhp90px) ([raw file](https://github.com/aodocs/endpoints-java/blob/4509ed86e94525f434d620926b85e6e1ef6f7d0a/endpoints-framework/src/main/java/com/google/api/server/spi/request/ServletRequestParamReader.java#L90)):*
<details><summary><i>Previously, alarribeau wrote…</i></summary><blockquote>

Interesting idea (to make the dependence optional).

Btw, I was reluctant to use this message interpolator implementation in the first place.

If we offer a way to provide/tune a custom validator I wouldn't even bother trying to instantiate this particular interpolator by reflection.
</blockquote></details>

Let's discuss this indeed.
___
*[endpoints-framework/src/test/java/com/google/api/server/spi/request/ServletRequestParamReaderTest.java, line 916 at r1](https://reviewable.io/reviews/aodocs/endpoints-java/59#-MnBA_RR5Z0wAncIqTdj:-MnVZizR6WzMlU2u6Dn5:b-pbdqz3) ([raw file](https://github.com/aodocs/endpoints-java/blob/4509ed86e94525f434d620926b85e6e1ef6f7d0a/endpoints-framework/src/test/java/com/google/api/server/spi/request/ServletRequestParamReaderTest.java#L916)):*
<details><summary><i>Previously, alarribeau wrote…</i></summary><blockquote>

Actually it was even easier to get rid of the method name. I think it is useless.
</blockquote></details>

Agreed.


<!-- Sent from Reviewable.io -->

2021-11-02 12:52 UTC, alarribeau reviewed
> *[Reviewable](https://reviewable.io/reviews/aodocs/endpoints-java/59)* status: 11 of 12 files reviewed, 2 unresolved discussions (waiting on @clementdenis)

___
*[endpoints-framework/build.gradle, line 106 at r1](https://reviewable.io/reviews/aodocs/endpoints-java/59#-MnB71XqCAaz36Nvp8Iv:-MnVgUhvAylG0eaZqpWu:b-896fix) ([raw file](https://github.com/aodocs/endpoints-java/blob/4509ed86e94525f434d620926b85e6e1ef6f7d0a/endpoints-framework/build.gradle#L106)):*
<details><summary><i>Previously, clementdenis (Clément Denis) wrote…</i></summary><blockquote>

We should probably ignore javax.validation from swagger-core then ...
</blockquote></details>

Done.
___
*[endpoints-framework/src/main/java/com/google/api/server/spi/request/ServletRequestParamReader.java, line 90 at r1](https://reviewable.io/reviews/aodocs/endpoints-java/59#-MnB8rxh3lubwjtvA8jP:-MnVgXbp3Ge5gRIHOsae:bcs5iq1) ([raw file](https://github.com/aodocs/endpoints-java/blob/4509ed86e94525f434d620926b85e6e1ef6f7d0a/endpoints-framework/src/main/java/com/google/api/server/spi/request/ServletRequestParamReader.java#L90)):*
<details><summary><i>Previously, clementdenis (Clément Denis) wrote…</i></summary><blockquote>

Let's discuss this indeed.
</blockquote></details>

As discussed, making the dependence optional is not that simple and would require either a lot complicate the usage of the feature (adding extra dependences + extra configuration).


<!-- Sent from Reviewable.io -->

2021-11-02 12:55 UTC, clementdenis approved these changes
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/aodocs/endpoints-java/59)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @alarribeau)



<!-- Sent from Reviewable.io -->

2021-11-02 12:56 UTC, merged